# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
    terraform {
      required_version = ">= 0.13.0"
      required_providers {
        kubernetes = {
          source  = "hashicorp/kubernetes"
          version = "~> 2.27.0"
        }
        helm = {
          source  = "hashicorp/helm"
          version = "~> 2.9.0"
       }
      }
    }

    provider "kubernetes" {
      config_context = "minikube"
      config_path    = "~/.kube/config" 
    }

    provider "helm" {
      kubernetes {
        config_path = "~/.kube/config"
      }
    }
